# Cluster diagnostics and model run review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/dnevo/clusters_unmixing/blob/main/notebooks/00_cluster_diagnostics.ipynb)

This notebook mirrors the scope of the original project notebook, but targets the slimmed project layout.

It covers:
- running the configured correlation experiments
- inspecting raw, normalized, and transformed cluster spectra
- comparing off-diagonal correlation statistics
- reviewing model metrics
- previewing abundance estimates and synthetic pixel spectra

In [1]:
# %load_ext autoreload
# %autoreload 2

import subprocess
import sys
from pathlib import Path

IN_COLAB = "google.colab" in sys.modules

if IN_COLAB:
    PROJECT_ROOT = Path("/content/clusters_unmixing")
    if not PROJECT_ROOT.exists():
        subprocess.check_call([
            "git",
            "clone",
            "https://github.com/dnevo/clusters_unmixing.git",
            str(PROJECT_ROOT),
        ])
else:
    NOTEBOOK_DIR = Path.cwd()
    PROJECT_ROOT = NOTEBOOK_DIR.parent if NOTEBOOK_DIR.name == "notebooks" else NOTEBOOK_DIR

SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from clusters_unmixing.utils import configure_notebook, default_config_path, run_diagnostics_notebook

configure_notebook(project_root=PROJECT_ROOT, autoreload=False)
CONFIG_PATH = default_config_path(PROJECT_ROOT)

In [2]:
artifacts = run_diagnostics_notebook(config_path=CONFIG_PATH, project_root=PROJECT_ROOT)

**Run name:** `cluster_corr_options`

**Output dir:** `H:\repos\clusters_unmixing\experiments\outputs\cluster_corr_options`

   run_index       cluster_set                                       bands_ranges   normalization transform  metric  mean_abs_offdiag  max_abs_offdiag  min_offdiag  max_offdiag
0          1  6clusters_thomas  [{"range_µm":[0.5,0.8],"reduce":"none"},{"rang...  with_quadratic       raw  cosine          0.704055         0.998960    -0.948256     0.998960
1          1  6clusters_thomas  [{"range_µm":[0.5,0.8],"reduce":"none"},{"rang...  with_quadratic       raw     sam         74.707716       161.487819     2.612848   161.487819

,run_index,cluster_set,bands_ranges,normalization,transform,snr_db,model,metric,mean,iterations_logged,last_active_pixels
0,1,6clusters_thomas,"[{""range_µm"":[0.5,0.8],""reduce"":""none""},{""rang...",with_quadratic,raw,inf,sunsal,abundance_rmse,0.001082,300,512
1,1,6clusters_thomas,"[{""range_µm"":[0.5,0.8],""reduce"":""none""},{""rang...",with_quadratic,raw,inf,sunsal,abundance_mae,0.000583,300,512
2,1,6clusters_thomas,"[{""range_µm"":[0.5,0.8],""reduce"":""none""},{""rang...",with_quadratic,raw,inf,vpgdu,abundance_rmse,0.064465,50,482
3,1,6clusters_thomas,"[{""range_µm"":[0.5,0.8],""reduce"":""none""},{""rang...",with_quadratic,raw,inf,vpgdu,abundance_mae,0.027090,50,482

---
## Run 1/1

        cluster_set                                       bands_ranges   normalization transform  num_pixels  snr_db         models
0  6clusters_thomas  [{"range_µm":[0.5,0.8],"reduce":"none"},{"rang...  with_quadratic       raw         512     inf  sunsal, vpgdu

            mean_abs_offdiag  max_abs_offdiag  min_offdiag  max_offdiag
stage
raw                 0.996241         0.999652     0.986813     0.999652
normalized          0.704036         0.998961    -0.948268     0.998961

### Model metrics

model             sunsal     vpgdu
metric
abundance_mae   0.000583  0.027090
abundance_rmse  0.001082  0.064465

### Abundance comparison by sampled pixel

### Abundances  |  pixel_index=37

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.000000     0.700000     0.000000     0.300000     0.000000     0.000000
1  sunsal                0.000765     0.000919     0.699212     0.000944     0.298924     0.000004    -0.000003
2   vpgdu                0.006702     0.006037     0.695205     0.008543     0.288402     0.001594     0.000220

### Abundances  |  pixel_index=46

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.200000     0.200000     0.300000     0.000000     0.100000     0.200000
1  sunsal                0.000626     0.200585     0.199039     0.300407     0.000738     0.099415     0.199815
2   vpgdu                0.034048     0.228385     0.149093     0.318923     0.045919     0.068933     0.188747

### Abundances  |  pixel_index=100

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.000000     0.000000     0.000000     1.000000     0.000000     0.000000
1  sunsal                0.000063    -0.000031     0.000093    -0.000052     0.999909     0.000050     0.000031
2   vpgdu                0.021323     0.007062     0.007519     0.010193     0.952704     0.014946     0.007576

### Abundances  |  pixel_index=283

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.000000     0.000000     0.000000     0.000000     1.000000     0.000000
1  sunsal                0.000262     0.000051     0.000061     0.000034     0.000023     0.999474     0.000357
2   vpgdu                0.176492     0.066951     0.020557     0.000000     0.038818     0.643148     0.230526

### Abundances  |  pixel_index=374

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.100000     0.000000     0.100000     0.000000     0.200000     0.600000
1  sunsal                0.000037     0.099960    -0.000007     0.100031     0.000003     0.200060     0.599953
2   vpgdu                0.018889     0.081764     0.012583     0.088415     0.000000     0.234764     0.582474

### Abundance error summary

    model  pixel_index      rmse       mae
0  sunsal           37  0.000765  0.000622
1   vpgdu           37  0.006702  0.005464
2  sunsal           46  0.000626  0.000577
3   vpgdu           46  0.034048  0.031076
4  sunsal          100  0.000063  0.000058
5   vpgdu          100  0.021323  0.015765
6  sunsal          283  0.000262  0.000175
7   vpgdu          283  0.176492  0.118951
8  sunsal          374  0.000037  0.000031
9   vpgdu          374  0.018889  0.015782

### Synthetic pixel spectra preview