# Cluster diagnostics and model run review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/dnevo/clusters_unmixing/blob/main/notebooks/00_cluster_diagnostics.ipynb)

This notebook mirrors the scope of the original project notebook, but targets the slimmed project layout.

It covers:
- running the configured correlation experiments
- inspecting raw, normalized, and transformed cluster spectra
- comparing off-diagonal correlation statistics
- reviewing model metrics
- previewing abundance estimates and synthetic pixel spectra

In [1]:
import subprocess
import sys
from pathlib import Path

IN_COLAB = "google.colab" in sys.modules

if IN_COLAB:
    PROJECT_ROOT = Path("/content/clusters_unmixing")
    if not PROJECT_ROOT.exists():
        subprocess.check_call([
            "git",
            "clone",
            "https://github.com/dnevo/clusters_unmixing.git",
            str(PROJECT_ROOT),
        ])
else:
    NOTEBOOK_DIR = Path.cwd()
    PROJECT_ROOT = NOTEBOOK_DIR.parent if NOTEBOOK_DIR.name == "notebooks" else NOTEBOOK_DIR

SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from clusters_unmixing.utils import setup_notebook_imports, run_diagnostics_notebook

project_root = setup_notebook_imports(project_root=PROJECT_ROOT)
CONFIG_PATH =  project_root / 'experiments' / 'configs' / 'correlation_options.yaml'

In [2]:
run_diagnostics_notebook(config_path=CONFIG_PATH, project_root=project_root)

**Run name:** `cluster_corr_options`

**Output dir:** `H:\repos\clusters_unmixing\experiments\outputs\cluster_corr_options`

---
## Run 1/1

                                                value
cluster set                          6clusters_thomas
bands          0.5-0.8 none, 1.2-1.6 mean, 2-2.5 none
normalization                          with_quadratic
transform                         pca(n_components=5)
pixels                                            512
snr                                             20 dB
models                                  sunsal, vpgdu

            mean_abs_offdiag  max_abs_offdiag  min_offdiag  max_offdiag
stage
raw                 0.996241         0.999652     0.986813     0.999652
normalized          0.704036         0.998961    -0.948268     0.998961
pca                 0.704110         0.998977    -0.948268     0.998977

### Model metrics

model             sunsal     vpgdu
metric
abundance_mae   0.154089  0.154942
abundance_rmse  0.234553  0.239508

### Abundance comparison by sampled pixel

### Abundances  |  pixel_index=37

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.000000     0.700000     0.000000     0.300000     0.000000     0.000000
1  sunsal                0.259329    -0.007759     0.513184     0.524533    -0.005102    -0.009294    -0.015562
2   vpgdu                0.228786     0.000000     0.550785     0.449215     0.000000     0.000000     0.000000

### Abundances  |  pixel_index=46

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.200000     0.200000     0.300000     0.000000      0.10000     0.200000
1  sunsal                0.120985     0.000004     0.361543     0.336461     0.000114     -0.00005     0.301929
2   vpgdu                0.321455     0.000000     0.000000     1.000000     0.000000      0.00000     0.000000

### Abundances  |  pixel_index=100

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.000000     0.000000     0.000000     1.000000     0.000000     0.000000
1  sunsal                0.481333    -0.000254     0.178516     0.512426    -0.000019     0.000135     0.309197
2   vpgdu                0.422895     0.000000     0.000000     0.645003     0.203685     0.000000     0.151311

### Abundances  |  pixel_index=283

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.000000     0.000000     0.000000     0.000000     1.000000     0.000000
1  sunsal                0.285536    -0.004478    -0.003456     0.238989    -0.000911     0.434622     0.335234
2   vpgdu                0.249287     0.000000     0.029912     0.158380     0.000000     0.500170     0.311538

### Abundances  |  pixel_index=374

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000      0.10000      0.00000     0.100000     0.000000     0.200000     0.600000
1  sunsal                0.187786      0.06031      0.00003    -0.000011    -0.000018     0.578267     0.361423
2   vpgdu                0.153964      0.08691      0.00000     0.000000     0.000000     0.507208     0.405882

### Synthetic pixel spectra preview