# Cluster diagnostics and model run review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/dnevo/clusters_unmixing/blob/main/notebooks/00_cluster_diagnostics.ipynb)

This notebook mirrors the scope of the original project notebook, but targets the slimmed project layout.

It covers:
- running the configured correlation experiments
- inspecting raw, normalized, and transformed cluster spectra
- comparing off-diagonal correlation statistics
- reviewing model metrics
- previewing abundance estimates and synthetic pixel spectra

In [1]:
import subprocess
import sys
from pathlib import Path

IN_COLAB = "google.colab" in sys.modules

if IN_COLAB:
    PROJECT_ROOT = Path("/content/clusters_unmixing")
    if not PROJECT_ROOT.exists():
        subprocess.check_call([
            "git",
            "clone",
            "https://github.com/dnevo/clusters_unmixing.git",
            str(PROJECT_ROOT),
        ])
else:
    NOTEBOOK_DIR = Path.cwd()
    PROJECT_ROOT = NOTEBOOK_DIR.parent if NOTEBOOK_DIR.name == "notebooks" else NOTEBOOK_DIR

SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from clusters_unmixing.utils import setup_notebook_imports, run_diagnostics_notebook

project_root = setup_notebook_imports(project_root=PROJECT_ROOT)
CONFIG_PATH =  project_root / 'experiments' / 'configs' / 'correlation_options.yaml'

In [2]:
artifacts = run_diagnostics_notebook(config_path=CONFIG_PATH, project_root=project_root)

**Run name:** `cluster_corr_options`

**Output dir:** `H:\repos\clusters_unmixing\experiments\outputs\cluster_corr_options`

,run_index,cluster_set,bands_ranges,normalization,transform,metric,mean_abs_offdiag,max_abs_offdiag,min_offdiag,max_offdiag
0,1,6clusters_thomas,"[{""range_µm"":[0.5,0.8],""reduce"":""none""},{""rang...",with_quadratic,pca(n_components=5),cosine,0.942021,0.999701,-0.999701,0.999085
1,1,6clusters_thomas,"[{""range_µm"":[0.5,0.8],""reduce"":""none""},{""rang...",with_quadratic,pca(n_components=5),sam,105.757201,178.598406,2.451773,178.598406

,run_index,cluster_set,bands_ranges,normalization,transform,snr_db,model,metric,mean,iterations_logged,last_active_pixels
0,1,6clusters_thomas,"[{""range_µm"":[0.5,0.8],""reduce"":""none""},{""rang...",with_quadratic,pca(n_components=5),inf,sunsal,abundance_rmse,0.000056,300,512
1,1,6clusters_thomas,"[{""range_µm"":[0.5,0.8],""reduce"":""none""},{""rang...",with_quadratic,pca(n_components=5),inf,sunsal,abundance_mae,0.000029,300,512
2,1,6clusters_thomas,"[{""range_µm"":[0.5,0.8],""reduce"":""none""},{""rang...",with_quadratic,pca(n_components=5),inf,vpgdu,abundance_rmse,0.154016,50,492
3,1,6clusters_thomas,"[{""range_µm"":[0.5,0.8],""reduce"":""none""},{""rang...",with_quadratic,pca(n_components=5),inf,vpgdu,abundance_mae,0.087225,50,492

---
## Run 1/1

        cluster_set                                       bands_ranges   normalization            transform  num_pixels  snr_db         models
0  6clusters_thomas  [{"range_µm":[0.5,0.8],"reduce":"none"},{"rang...  with_quadratic  pca(n_components=5)         512     inf  sunsal, vpgdu

            mean_abs_offdiag  max_abs_offdiag  min_offdiag  max_offdiag
stage
raw                 0.996241         0.999652     0.986813     0.999652
normalized          0.704036         0.998961    -0.948268     0.998961
pca                 0.942021         0.999701    -0.999701     0.999085

### Model metrics

model             sunsal     vpgdu
metric
abundance_mae   0.000029  0.087225
abundance_rmse  0.000056  0.154016

### Abundance comparison by sampled pixel

### Abundances  |  pixel_index=37

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.000000     0.700000     0.000000     0.300000     0.000000     0.000000
1  sunsal                0.000030     0.000025     0.699975     0.000023     0.299961     0.000039    -0.000023
2   vpgdu                0.054729     0.045157     0.584660     0.042125     0.289841     0.015847     0.022370

### Abundances  |  pixel_index=46

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.200000     0.200000     0.300000     0.000000     0.100000     0.200000
1  sunsal                0.000019     0.199988     0.200024     0.299989     0.000000     0.099973     0.200026
2   vpgdu                0.003561     0.196725     0.201915     0.295153     0.003721     0.104504     0.197983

### Abundances  |  pixel_index=100

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.000000     0.000000     0.000000     1.000000     0.000000     0.000000
1  sunsal                0.000038     0.000027     0.000017     0.000003     0.999917     0.000011     0.000025
2   vpgdu                0.242541     0.074468     0.136472     0.081052     0.462266     0.160721     0.085021

### Abundances  |  pixel_index=283

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.000000     0.000000     0.000000     0.000000     1.000000     0.000000
1  sunsal                0.000242     0.000031     0.000080     0.000017     0.000015     0.999521     0.000336
2   vpgdu                0.447215     0.199135     0.202073     0.199444     0.198879     0.000000     0.200470

### Abundances  |  pixel_index=374

   source  abundance_rmse_vs_true  endmember_1  endmember_2  endmember_3  endmember_4  endmember_5  endmember_6
0    true                0.000000     0.100000     0.000000     0.100000     0.000000     0.200000     0.600000
1  sunsal                0.000114     0.100061    -0.000078     0.100041     0.000114     0.199782     0.600080
2   vpgdu                0.006269     0.088634     0.000307     0.097190     0.002775     0.201711     0.609382

### Abundance error summary

    model  pixel_index      rmse       mae
0  sunsal           37  0.000030  0.000029
1   vpgdu           37  0.054729  0.041833
2  sunsal           46  0.000019  0.000017
3   vpgdu           46  0.003561  0.003380
4  sunsal          100  0.000038  0.000028
5   vpgdu          100  0.242541  0.179245
6  sunsal          283  0.000242  0.000160
7   vpgdu          283  0.447215  0.333333
8  sunsal          374  0.000114  0.000099
9   vpgdu          374  0.006269  0.004725

### Synthetic pixel spectra preview